# Generated by Django 2.1.7 on 2019-02-22 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='tittle',
            field=models.CharField(max_length=100),
        ),
    ]
