# Generated by Django 2.1.7 on 2019-02-25 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='helpfultopic',
            name='helpful',
            field=models.BooleanField(default=False),
        ),
    ]
