# Generated by Django 2.1.7 on 2019-02-22 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0002_auto_20190222_1746'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='tittle',
            new_name='title',
        ),
    ]
